sonar.projectKey=Affy657_Movie-Picker
sonar.organization=affy657
sonar.host.url=https://sonarcloud.io

sonar.sources=apps/web/src,apps/api-dotnet
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.min.js
sonar.tests=apps/web/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info
sonar.cs.opencover.reportsPaths=apps/api-dotnet/MoviePicker.Tests/TestResults/coverage.opencover.xml
